package slosar.srt.spendingsapp.DbModule;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig spendingDaoConfig;
    private final DaoConfig categoryDaoConfig;

    private final SpendingDao spendingDao;
    private final CategoryDao categoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        spendingDaoConfig = daoConfigMap.get(SpendingDao.class).clone();
        spendingDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        spendingDao = new SpendingDao(spendingDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);

        registerDao(Spending.class, spendingDao);
        registerDao(Category.class, categoryDao);
    }

    public void clear() {
        spendingDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
    }

    public SpendingDao getSpendingDao() {
        return spendingDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

}
